@ClassDemoMusicRest_HostAddress = http://localhost:5173

GET {{ClassDemoMusicRest_HostAddress}}/weatherforecast/
Accept: application/json

###

@id=0
GET {{ClassDemoMusicRest_HostAddress}}/api/musics/{{id}}

###
